title: Campus Info
description: 最新动态针对学院工作、求职、竞赛、通知等事务。
author: Coshpr

domain: "pzding.top"
baseurl: ""
email: "pzding@163.com"

twitter_hashtag: machinelearning
github_username: Coshpr
github_repo: campus_info

markdown: kramdown
ga_id:

include: ['_pages']
